version: '3.5'

services:

  civitas:
    depends_on:
      - mariadb
    build: 
      context: .
    hostname: civitas
    ports:
      - 8080:80
    volumes:
      - ./src/:/var/www/html/
    environment:
      - TMDB_API_KEY=key
      - GOOGLE_BOOKS_API_KEY=key
      - MYSQL_ROOT_PASSWORD=rpsswd
      - DB_NAME=civitas
  
  mariadb:
    image: mariadb:latest
    hostname: db
    ports:
      - 6000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rpsswd
    volumes:
      - ./data-models/civitasData.sql:/docker-entrypoint-initdb.d/civitasData.sql

networks:
  default:
    driver: bridge
    name: civitas-network