version: '3.7'

services:

  civitas:
    depends_on:
      - mariadb
    build: 
      context: .
    hostname: civitas
    ports:
      - 8000:80
    volumes:
      - ./src/:/var/www/html/
    environment:
      - TMDB_API_KEY=key
      - GOOGLE_BOOKS_API_KEY=key
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=rpsswd
      - DB_NAME=civitas
      - DB_HOSTNAME=db
  
  mariadb:
    image: mariadb:latest
    hostname: db
    ports:
      - 6000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rpsswd
    volumes:
      - ./data-models/civitasData.sql:/docker-entrypoint-initdb.d/civitasData.sql
  
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mariadb
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

networks:
  default:
    driver: bridge
    name: civitas-network
