version: '3.5'

services:

  civitas:
    build: 
      context: .
    hostname: civitas
    ports:
      - 8080:80
    volumes:
      - ../:/var/www/html/
    enviroment:
      - TMDB_API_KEY=your_key
      - GOOGLE_BOOKS_API_KEY=your_key
      - MYSQL_ROOT_PASSWORD=rpsswd
      - MYSQL_USER=user
      - MYSQL_PASSWORD=upsswd
      - DB_NAME=civitas
  
  mariadb:
    image: mariadb:latest
    hostname: db
    ports:
      - 6000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rpsswd
      - MYSQL_USER=user
      - MYSQL_PASSWORD=upsswd

networks:
  default:
    driver: bridge
    name: civitas-network
