version: '3'
services:
  web:
    container_name: civitas_web
    build:
      context: web
    networks:
      - civitas-network
    volumes:
      - ../:/var/www/html/
    ports:
      - 8080:80

  db:
    container_name: civitas_db
    build:
      context: db
    networks:
      - civitas-network
    ports:
      - 6000:3306

networks:
  civitas-network:
    driver: bridge 

#Devido à necessidade de terminal interativo não é possível instalar o php no container a partir do indicador RUN do Dockerfile, portanto, execute o seguinte comando após os containers estarem online: docker exec -it civitas_web bash -c "apt install -y php libapache2-mod-php php-mysql && exit" && docker restart civitas_web
